### ISSUE TITLE
Instagram Downloader : After downloading 1 video not able to download second video

### ISSUE THREAD

**Issue by s4suryapal** [chauhanshivam079/I-Bot#4]
After downloading 1 video. Insta Downloader not working

**Comment by chauhanshivam079** [comment]
Is that video private?

**Comment by chauhanshivam079** [comment]
some captcha issue was there. Fixed now

**Comment by s4suryapal** [comment]
I just tested on +918920693499. But no reply from BOT, may it's crashed or something. And still Instagram downloader not working
